steps:
  - wait
  - label: ":hammer_and_wrench: :packer: validate"
    command: make validate
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - wait
  - label: ":hammer_and_wrench: Build macos-10.12"
    command: .buildkite/build-base.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - wait
  - label: ":hammer_and_wrench: Build macos-10.12 w/ xcode 8.3.3"
    command: .buildkite/build-xcode.sh 8.3.3
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

